[project]
name = "sas"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { email = "christoph.werner.stein@gmail.com" }
]
requires-python = ">=3.9"
dependencies = [
    "numpy>=2.0.2",
]

[project.scripts]
sas = "sas:main"

[build-system]
requires = ["uv_build>=0.11.32,<0.12.0"]
build-backend = "uv_build"
