[project]
name = "sas"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { email = "christoph.stein@jku.at" }
]
requires-python = ">=3.11"
dependencies = [
    "click>=8.1.8",
    "matplotlib>=3.9.4",
    "networkx>=3.2.1",
    "numpy>=2.0.2",
    "qiskit>=2.2.3",
    "qiskit-aer>=0.17.2",
    "scikit-learn>=1.9.0",
    "scipy>=1.17.1",
    "torch>=2.13.0",
    "tqdm>=4.70.0",
]

[project.scripts]
sas = "sas:main"

[build-system]
requires = ["uv_build>=0.11.32,<0.12.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "matplotlib>=3.11.1",
    "pandas>=3.0.5",
]
