from .interface import ISurrogate
from .circuit_feature_surrogate import CircuitFeatureSurrogate, CIRCUIT_FEATURE_SURROGATE
from .vector_surrogate import StateVectorSurrogate, STATE_VECTOR_SURROGATE
from .shot_distance_surrogate import SHOT_DISTANCE_SURROGATE, ShotDistanceSurrogate
from .random_fitness import RandomFitnessSurrogate, RANDOM_FITNESS_SURROGATE
from .gnn_surrogate import GNN_SURROGATE, GNNSurrogate
from .calibrated_state_vector import CALIBRATED_STATE_VECTOR_SURROGATE, CalibratedStateVectorSurrogate
from .random_base_state_surrogate import RANDOM_BASE_STATE_SURROGATE, RandomBaseStateSurrogate
from .multi_base_state_surrogate import MULTI_BASE_STATE_SURROGATE, MultiBaseStateSurrogate
